### ISSUE TITLE
Blay's Waystones Support

### ISSUE THREAD

**Issue by ClockworkCorvus** [sleepingdragoninn/surveystones#2]
I do not know how difficult it would be to add support through sinytra to allow the automatic marking of forge waystones (https://modrinth.com/mod/waystones), but I feel like it'd be a logical extension for this mod, if it is possible anyways.

**Comment by sleepingdragoninn** [comment]
Hmm, difficult to know how hard it is to add explicit compatibility with a forge mod as a connector mod - but seeing as they have a fabric version, and this library is pretty flexible now, I'll give it a go.

Might need to rename the mod to "Surveystones" lol

**Comment by ClockworkCorvus** [comment]
Surveystones has a really nice ring to it, ngl.

**Comment by sleepingdragoninn** [comment]
it's been done! https://modrinth.com/mod/surveystones/version/1.3.0+1.20
