### ISSUE TITLE
Inability to delete a marker from Waystones

### ISSUE THREAD

**Issue by TovarishchF** [sleepingdragoninn/surveystones#4]
I placed down a waystone and named it. Much later I relocated it (broke it and placed somewhere else) and noticed that the marker from the first waystone didn't disappear. I tried to delete it with the tool from Antique Atlas 4, but it didn't work. I also tried to delete Surveystones from mods folder itself, however after such actions the game crashed when I tried to enter my world.

**Comment by sleepingdragoninn** [comment]
breaking the waystone should remove the marker, so that's the bug - delete `data/landmarks.dat` to clear custom waypoints and the broken waystones marker.

Please recreate the bug on a fresh instance and post your logs/latest.log to mclo.gs

**Comment by sleepingdragoninn** [comment]
oh yeah - we double-fixed this - update to latest surveyor

you can now manually remove global landmarks if you have op - use /surveyor landmarks get (type) and then /surveyor landmarks remove

secondly, landmark deletion has been fixed to synchronise even if you were offline for their removal. oops.

Let me know if that fixes it!
